### ISSUE TITLE
READMEを追加する

### ISSUE THREAD

**Issue by KATO-Hiro** [not522/ac-library-python#3]
## WHY

+ ライブラリを利用する人たち（開発・保守メンバーを含む）に向けて、使いかたなどの説明があったほうがいいと思われるため

### READMEを記述する言語

+ 英語のみ
+ 日本語のみ
+ 英語と日本語を別ページで用意する

###  READMEに記述する内容の候補

+ リポジトリ名
+ 概要とDEMO
+ 対応しているライブラリの一覧と進捗状況
+ 使い方
+ FAQ
+ 開発・実行環境
  + ライブラリの利用者が必要なもの
  + ライブラリの開発・保守メンバーが必要なもの
+ リポジトリへの貢献方法
+ 連絡先
+ 参考資料や関連プロジェクトへのリンク
+ ライセンスへのリンク

### 質問

+ リポジトリのREADMEには、[こちらのレポジトリ](https://github.com/online-judge-tools/verification-helper)のように英語と日本語を別ページで用意するという形がいいように思いますが、どのようにお考えでしょうか?

+ READMEの内容として、不足しているもの・冗長なものがあれば、教えていただけますでしょうか?

**Comment by not522** [comment]
Closed by #4.
